mytwitter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweets.urls')),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = 'tweets'
urlpatterns = [
    path('', views.index, name='index'),
    path('tweets', views.list, name='list'),
    path('tweets/create', views.create, name='create'),
]

tweets/models.py
from django.db import models

class Tweet(models.Model):
    text = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

tweets/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect

from .models import Tweet

def index(request):
    return render(request, 'index.html')

def list(request):
    tweets = Tweet.objects.order_by('-created_at').all()
    return render(request, 'tweets.html', { 'tweets': tweets })

def create(request):
    tweet = Tweet()
    tweet.text = request.POST.get('tweet', None)
    tweet.save()

    return HttpResponseRedirect(reverse('tweets:list'))

tweets/templates/index.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            :root {
                --black: #555;
                --white: #fff;
            }

            html {
                box-sizing: border-box;
            }

            * {
                box-sizing: inherit;
            }

            body {
                padding: 0;
                margin: 0;
                font-size: 16px;
                min-height: 100vh;
                min-width: 100vw;
            }
            
            .container {
                height: 100%;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
            }

            .title {
                text-align: center;
                font-size: 6rem;
                color: var(--black);
            }

            .btn {
                font-family: sans-serif;
                padding: 1rem 3rem;
                background: var(--black);
                color: var(--white);
                text-decoration: none;
                text-transform: uppercase;
                font-size: 1.25rem;
                border-radius: .5rem;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1 class="title">Hello to MyTwitter!</h1>
            <a class="btn" href="{% url 'tweets:list' %}">See tweets</a>
        </div>
    </body>
</html>

tweets/templates/tweets.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            :root {
                --black: #555;
                --shadow: #333;
                --white: #fff;
                --gray:  #eee;
            }

            html {
                box-sizing: border-box;
            }

            * {
                box-sizing: inherit;
            }

            body {
                padding: 0;
                margin: 0;
                font-size: 16px;
                min-height: 100vh;
                min-width: 100vw;
                font-family: sans-serif;
            }
            
            .container {
                height: 100%;
                padding: 2rem;
                max-width: 48rem;
                margin: 0 auto;
            }

            .tweet-form {
                display: flex;
                flex-direction: column;
            }

            textarea {
                background: var(--gray);
                padding: 1rem;
                min-height: 5rem;
                font-size: 1.25rem;
                border: 0;
                border-top-left-radius: .5rem;
                border-top-right-radius: .5rem;
            }

            button {
                background: var(--black);
                padding: .5rem 1rem;
                color: var(--white);
                border: 0;
                border-bottom: .25rem solid var(--shadow);
                text-transform: uppercase;
                font-weight: bold;
                font-size: 1rem;
                border-bottom-left-radius: .5rem;
                border-bottom-right-radius: .5rem;
                cursor: pointer;
            }
            
            .tweet-list {
                margin-top: 2rem;
            }

            .tweet {
                display: flex;
                flex-direction: column;
            }

            .tweet:not(:last-of-type) {
                margin-bottom: 2rem;
            }
            
            .tweet p {
                margin: 0;
                margin-bottom: .5rem;
            }

            .tweet small {
                align-self: flex-end;
            }

            .btn {
                display: inline-block;
                font-family: sans-serif;
                padding: 0.5rem 1rem;
                background: var(--black);
                color: var(--white);
                text-decoration: none;
                text-transform: uppercase;
                font-size: .8rem;
                margin-bottom: 1rem;
                border-radius: .5rem;
            }

            .tweet-empty {
                text-align: center;
                padding: 2rem;
                font-style: italic;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <a href="{% url 'tweets:index' %}" class="btn">&lt; Back to home</a>
            <form class="tweet-form" action="{% url 'tweets:create' %}" method="post">
                {% csrf_token %}
                <textarea name="tweet"></textarea>
                <button type="submit">Tweet!</button>
            </form>
            <div class="tweet-list">
                {% for tweet in tweets %}
                    <div class="tweet">
                        <p class="content">{{ tweet.text }}</p>
                        <small>{{ tweet.created_at | timesince }} ago</small>
                    </div>
                {% empty %}
                    <div class="tweet-empty">Be the first to tweet!</div>
                {% endfor %}
            </div>
        </div>
    </body>
</html>